// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: incentive/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_UnUniFi_chain_types "github.com/UnUniFi/chain/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgClaimCdpMintingReward struct {
	Sender         github_com_UnUniFi_chain_types.StringAccAddress `protobuf:"bytes,1,opt,name=sender,proto3,customtype=github.com/UnUniFi/chain/types.StringAccAddress" json:"sender" yaml:"sender"`
	MultiplierName string                                          `protobuf:"bytes,2,opt,name=multiplier_name,json=multiplierName,proto3" json:"multiplier_name,omitempty" yaml:"multiplier_name"`
}

func (m *MsgClaimCdpMintingReward) Reset()         { *m = MsgClaimCdpMintingReward{} }
func (m *MsgClaimCdpMintingReward) String() string { return proto.CompactTextString(m) }
func (*MsgClaimCdpMintingReward) ProtoMessage()    {}
func (*MsgClaimCdpMintingReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_910d537256618935, []int{0}
}
func (m *MsgClaimCdpMintingReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimCdpMintingReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimCdpMintingReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimCdpMintingReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimCdpMintingReward.Merge(m, src)
}
func (m *MsgClaimCdpMintingReward) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimCdpMintingReward) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimCdpMintingReward.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimCdpMintingReward proto.InternalMessageInfo

func (m *MsgClaimCdpMintingReward) GetMultiplierName() string {
	if m != nil {
		return m.MultiplierName
	}
	return ""
}

type MsgClaimCdpMintingRewardResponse struct {
}

func (m *MsgClaimCdpMintingRewardResponse) Reset()         { *m = MsgClaimCdpMintingRewardResponse{} }
func (m *MsgClaimCdpMintingRewardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimCdpMintingRewardResponse) ProtoMessage()    {}
func (*MsgClaimCdpMintingRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_910d537256618935, []int{1}
}
func (m *MsgClaimCdpMintingRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimCdpMintingRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimCdpMintingRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimCdpMintingRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimCdpMintingRewardResponse.Merge(m, src)
}
func (m *MsgClaimCdpMintingRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimCdpMintingRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimCdpMintingRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimCdpMintingRewardResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgClaimCdpMintingReward)(nil), "botany.incentive.MsgClaimCdpMintingReward")
	proto.RegisterType((*MsgClaimCdpMintingRewardResponse)(nil), "botany.incentive.MsgClaimCdpMintingRewardResponse")
}

func init() { proto.RegisterFile("incentive/tx.proto", fileDescriptor_910d537256618935) }

var fileDescriptor_910d537256618935 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x6a, 0xeb, 0x30,
	0x14, 0xc6, 0xed, 0x7b, 0x21, 0x70, 0x0d, 0xf7, 0xde, 0x62, 0xda, 0x12, 0x3c, 0xd8, 0xc1, 0x53,
	0xc9, 0x60, 0x91, 0x74, 0xeb, 0x96, 0xa4, 0x94, 0x2e, 0xe9, 0xe0, 0x92, 0xa5, 0x4b, 0x2b, 0xdb,
	0xa7, 0xca, 0x01, 0x4b, 0x32, 0x96, 0xf2, 0x6f, 0xe9, 0x33, 0xf4, 0x95, 0xba, 0x65, 0xcc, 0x58,
	0x3a, 0x98, 0x92, 0xbc, 0x41, 0x9e, 0xa0, 0xc4, 0x4e, 0xff, 0x10, 0x1a, 0xe8, 0x26, 0x9d, 0xef,
	0xa7, 0xef, 0x70, 0x3e, 0x1d, 0xcb, 0x46, 0x11, 0x83, 0xd0, 0x38, 0x06, 0xa2, 0xa7, 0x41, 0x96,
	0x4b, 0x2d, 0xed, 0x83, 0x48, 0x6a, 0x2a, 0x66, 0xc1, 0x87, 0xe4, 0x1c, 0x32, 0xc9, 0x64, 0x29,
	0x92, 0xcd, 0xa9, 0xe2, 0x1c, 0x8f, 0x49, 0xc9, 0x52, 0x20, 0xe5, 0x2d, 0x1a, 0xdd, 0x13, 0x8d,
	0x1c, 0x94, 0xa6, 0x3c, 0xdb, 0x02, 0x6e, 0x2c, 0x15, 0x97, 0x8a, 0x44, 0x54, 0x01, 0x19, 0xb7,
	0x22, 0xd0, 0xb4, 0x45, 0x62, 0x89, 0xa2, 0xd2, 0xfd, 0x27, 0xd3, 0xaa, 0xf7, 0x15, 0xeb, 0xa5,
	0x14, 0x79, 0x2f, 0xc9, 0xfa, 0x28, 0x34, 0x0a, 0x16, 0xc2, 0x84, 0xe6, 0x89, 0x7d, 0x67, 0xd5,
	0x14, 0x88, 0x04, 0xf2, 0xba, 0xd9, 0x30, 0x4f, 0xfe, 0x74, 0x2f, 0xe7, 0x85, 0x67, 0xbc, 0x14,
	0x1e, 0x61, 0xa8, 0x87, 0xa3, 0x28, 0x88, 0x25, 0x27, 0x03, 0x31, 0x10, 0x78, 0x81, 0x24, 0x1e,
	0x52, 0x14, 0x44, 0xcf, 0x32, 0x50, 0xc1, 0xb5, 0xce, 0x51, 0xb0, 0x4e, 0x1c, 0x77, 0x92, 0x24,
	0x07, 0xa5, 0xd6, 0x85, 0xf7, 0x77, 0x46, 0x79, 0x7a, 0xe6, 0x57, 0x76, 0x7e, 0xb8, 0xf5, 0xb5,
	0x7b, 0xd6, 0x7f, 0x3e, 0x4a, 0x35, 0x66, 0x29, 0x42, 0x7e, 0x2b, 0x28, 0x87, 0xfa, 0xaf, 0xb2,
	0x95, 0xb3, 0x2e, 0xbc, 0xe3, 0xea, 0xcd, 0x0e, 0xe0, 0x87, 0xff, 0x3e, 0x2b, 0x57, 0x9b, 0x82,
	0x6f, 0x35, 0xf6, 0x8d, 0x10, 0x82, 0xca, 0xa4, 0x50, 0xd0, 0x7e, 0xb0, 0x7e, 0xf7, 0x15, 0xb3,
	0x27, 0xd6, 0xd1, 0xf7, 0xa3, 0x36, 0x83, 0xdd, 0xc4, 0x83, 0x7d, 0x9e, 0x4e, 0xfb, 0xe7, 0xec,
	0x7b, 0xff, 0xee, 0xf9, 0x7c, 0xe9, 0x9a, 0x8b, 0xa5, 0x6b, 0xbe, 0x2e, 0x5d, 0xf3, 0x71, 0xe5,
	0x1a, 0x8b, 0x95, 0x6b, 0x3c, 0xaf, 0x5c, 0xe3, 0xa6, 0xb9, 0x37, 0xcc, 0x29, 0xf9, 0xb2, 0x19,
	0x9b, 0x60, 0xa3, 0x5a, 0xf9, 0x69, 0xa7, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x21, 0x4c,
	0xcf, 0x33, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ClaimCdpMintingReward(ctx context.Context, in *MsgClaimCdpMintingReward, opts ...grpc.CallOption) (*MsgClaimCdpMintingRewardResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimCdpMintingReward(ctx context.Context, in *MsgClaimCdpMintingReward, opts ...grpc.CallOption) (*MsgClaimCdpMintingRewardResponse, error) {
	out := new(MsgClaimCdpMintingRewardResponse)
	err := c.cc.Invoke(ctx, "/botany.incentive.Msg/ClaimCdpMintingReward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ClaimCdpMintingReward(context.Context, *MsgClaimCdpMintingReward) (*MsgClaimCdpMintingRewardResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimCdpMintingReward(ctx context.Context, req *MsgClaimCdpMintingReward) (*MsgClaimCdpMintingRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimCdpMintingReward not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimCdpMintingReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimCdpMintingReward)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimCdpMintingReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.incentive.Msg/ClaimCdpMintingReward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimCdpMintingReward(ctx, req.(*MsgClaimCdpMintingReward))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "botany.incentive.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimCdpMintingReward",
			Handler:    _Msg_ClaimCdpMintingReward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "incentive/tx.proto",
}

func (m *MsgClaimCdpMintingReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimCdpMintingReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimCdpMintingReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MultiplierName) > 0 {
		i -= len(m.MultiplierName)
		copy(dAtA[i:], m.MultiplierName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MultiplierName)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Sender.Size()
		i -= size
		if _, err := m.Sender.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgClaimCdpMintingRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimCdpMintingRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimCdpMintingRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimCdpMintingReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Sender.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.MultiplierName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimCdpMintingRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimCdpMintingReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimCdpMintingReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimCdpMintingReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sender.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiplierName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiplierName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimCdpMintingRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimCdpMintingRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimCdpMintingRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
