// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ecosystemincentive/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params" yaml:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryIncentiveUnitRequest struct {
	IncentiveUnitId string `protobuf:"bytes,1,opt,name=incentive_unit_id,json=incentiveUnitId,proto3" json:"incentive_unit_id,omitempty" yaml:"incentive_unit_id"`
}

func (m *QueryIncentiveUnitRequest) Reset()         { *m = QueryIncentiveUnitRequest{} }
func (m *QueryIncentiveUnitRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIncentiveUnitRequest) ProtoMessage()    {}
func (*QueryIncentiveUnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{2}
}
func (m *QueryIncentiveUnitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIncentiveUnitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIncentiveUnitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIncentiveUnitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIncentiveUnitRequest.Merge(m, src)
}
func (m *QueryIncentiveUnitRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIncentiveUnitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIncentiveUnitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIncentiveUnitRequest proto.InternalMessageInfo

func (m *QueryIncentiveUnitRequest) GetIncentiveUnitId() string {
	if m != nil {
		return m.IncentiveUnitId
	}
	return ""
}

type QueryIncentiveUnitResponse struct {
	IncentiveUnit *IncentiveUnit `protobuf:"bytes,1,opt,name=incentive_unit,json=incentiveUnit,proto3" json:"incentive_unit,omitempty" yaml:"incentive_unit"`
}

func (m *QueryIncentiveUnitResponse) Reset()         { *m = QueryIncentiveUnitResponse{} }
func (m *QueryIncentiveUnitResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIncentiveUnitResponse) ProtoMessage()    {}
func (*QueryIncentiveUnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{3}
}
func (m *QueryIncentiveUnitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIncentiveUnitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIncentiveUnitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIncentiveUnitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIncentiveUnitResponse.Merge(m, src)
}
func (m *QueryIncentiveUnitResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIncentiveUnitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIncentiveUnitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIncentiveUnitResponse proto.InternalMessageInfo

func (m *QueryIncentiveUnitResponse) GetIncentiveUnit() *IncentiveUnit {
	if m != nil {
		return m.IncentiveUnit
	}
	return nil
}

type QueryAllRewardsRequest struct {
	SubjectAddr string `protobuf:"bytes,1,opt,name=subject_addr,json=subjectAddr,proto3" json:"subject_addr,omitempty" yaml:"subject_addr"`
}

func (m *QueryAllRewardsRequest) Reset()         { *m = QueryAllRewardsRequest{} }
func (m *QueryAllRewardsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRewardsRequest) ProtoMessage()    {}
func (*QueryAllRewardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{4}
}
func (m *QueryAllRewardsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRewardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRewardsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRewardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRewardsRequest.Merge(m, src)
}
func (m *QueryAllRewardsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRewardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRewardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRewardsRequest proto.InternalMessageInfo

func (m *QueryAllRewardsRequest) GetSubjectAddr() string {
	if m != nil {
		return m.SubjectAddr
	}
	return ""
}

type QueryAllRewardsResponse struct {
	Rewards RewardStore `protobuf:"bytes,1,opt,name=rewards,proto3" json:"rewards" yaml:"rewards"`
}

func (m *QueryAllRewardsResponse) Reset()         { *m = QueryAllRewardsResponse{} }
func (m *QueryAllRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRewardsResponse) ProtoMessage()    {}
func (*QueryAllRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{5}
}
func (m *QueryAllRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRewardsResponse.Merge(m, src)
}
func (m *QueryAllRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRewardsResponse proto.InternalMessageInfo

func (m *QueryAllRewardsResponse) GetRewards() RewardStore {
	if m != nil {
		return m.Rewards
	}
	return RewardStore{}
}

type QueryRewardRequest struct {
	SubjectAddr string `protobuf:"bytes,1,opt,name=subject_addr,json=subjectAddr,proto3" json:"subject_addr,omitempty" yaml:"subject_addr"`
	Denom       string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty" yaml:"denom"`
}

func (m *QueryRewardRequest) Reset()         { *m = QueryRewardRequest{} }
func (m *QueryRewardRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRewardRequest) ProtoMessage()    {}
func (*QueryRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{6}
}
func (m *QueryRewardRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardRequest.Merge(m, src)
}
func (m *QueryRewardRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardRequest proto.InternalMessageInfo

func (m *QueryRewardRequest) GetSubjectAddr() string {
	if m != nil {
		return m.SubjectAddr
	}
	return ""
}

func (m *QueryRewardRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryRewardResponse struct {
	Reward types.Coin `protobuf:"bytes,1,opt,name=reward,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"reward" yaml:"reward"`
}

func (m *QueryRewardResponse) Reset()         { *m = QueryRewardResponse{} }
func (m *QueryRewardResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRewardResponse) ProtoMessage()    {}
func (*QueryRewardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{7}
}
func (m *QueryRewardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardResponse.Merge(m, src)
}
func (m *QueryRewardResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardResponse proto.InternalMessageInfo

func (m *QueryRewardResponse) GetReward() types.Coin {
	if m != nil {
		return m.Reward
	}
	return types.Coin{}
}

type QueryRecordedIncentiveUnitIdRequest struct {
	ClassId string `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty" yaml:"class_id"`
	NftId   string `protobuf:"bytes,2,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty" yaml:"nft_id"`
}

func (m *QueryRecordedIncentiveUnitIdRequest) Reset()         { *m = QueryRecordedIncentiveUnitIdRequest{} }
func (m *QueryRecordedIncentiveUnitIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecordedIncentiveUnitIdRequest) ProtoMessage()    {}
func (*QueryRecordedIncentiveUnitIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{8}
}
func (m *QueryRecordedIncentiveUnitIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecordedIncentiveUnitIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecordedIncentiveUnitIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecordedIncentiveUnitIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordedIncentiveUnitIdRequest.Merge(m, src)
}
func (m *QueryRecordedIncentiveUnitIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecordedIncentiveUnitIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordedIncentiveUnitIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordedIncentiveUnitIdRequest proto.InternalMessageInfo

func (m *QueryRecordedIncentiveUnitIdRequest) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *QueryRecordedIncentiveUnitIdRequest) GetNftId() string {
	if m != nil {
		return m.NftId
	}
	return ""
}

type QueryRecordedIncentiveUnitIdResponse struct {
	IncentiveUnitId string `protobuf:"bytes,1,opt,name=incentive_unit_id,json=incentiveUnitId,proto3" json:"incentive_unit_id,omitempty" yaml:"incentive_unit_id"`
}

func (m *QueryRecordedIncentiveUnitIdResponse) Reset()         { *m = QueryRecordedIncentiveUnitIdResponse{} }
func (m *QueryRecordedIncentiveUnitIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecordedIncentiveUnitIdResponse) ProtoMessage()    {}
func (*QueryRecordedIncentiveUnitIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{9}
}
func (m *QueryRecordedIncentiveUnitIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecordedIncentiveUnitIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecordedIncentiveUnitIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecordedIncentiveUnitIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordedIncentiveUnitIdResponse.Merge(m, src)
}
func (m *QueryRecordedIncentiveUnitIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecordedIncentiveUnitIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordedIncentiveUnitIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordedIncentiveUnitIdResponse proto.InternalMessageInfo

func (m *QueryRecordedIncentiveUnitIdResponse) GetIncentiveUnitId() string {
	if m != nil {
		return m.IncentiveUnitId
	}
	return ""
}

type QueryIncentiveUnitIdsByAddrRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
}

func (m *QueryIncentiveUnitIdsByAddrRequest) Reset()         { *m = QueryIncentiveUnitIdsByAddrRequest{} }
func (m *QueryIncentiveUnitIdsByAddrRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIncentiveUnitIdsByAddrRequest) ProtoMessage()    {}
func (*QueryIncentiveUnitIdsByAddrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{10}
}
func (m *QueryIncentiveUnitIdsByAddrRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIncentiveUnitIdsByAddrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIncentiveUnitIdsByAddrRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIncentiveUnitIdsByAddrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIncentiveUnitIdsByAddrRequest.Merge(m, src)
}
func (m *QueryIncentiveUnitIdsByAddrRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIncentiveUnitIdsByAddrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIncentiveUnitIdsByAddrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIncentiveUnitIdsByAddrRequest proto.InternalMessageInfo

func (m *QueryIncentiveUnitIdsByAddrRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryIncentiveUnitIdsByAddrResponse struct {
	IncentiveUnitIdsByAddr IncentiveUnitIdsByAddr `protobuf:"bytes,1,opt,name=incentive_unit_ids_by_addr,json=incentiveUnitIdsByAddr,proto3" json:"incentive_unit_ids_by_addr" yaml:"incentive_unit_ids_by_addr"`
}

func (m *QueryIncentiveUnitIdsByAddrResponse) Reset()         { *m = QueryIncentiveUnitIdsByAddrResponse{} }
func (m *QueryIncentiveUnitIdsByAddrResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIncentiveUnitIdsByAddrResponse) ProtoMessage()    {}
func (*QueryIncentiveUnitIdsByAddrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12077848d3534579, []int{11}
}
func (m *QueryIncentiveUnitIdsByAddrResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIncentiveUnitIdsByAddrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIncentiveUnitIdsByAddrResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIncentiveUnitIdsByAddrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIncentiveUnitIdsByAddrResponse.Merge(m, src)
}
func (m *QueryIncentiveUnitIdsByAddrResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIncentiveUnitIdsByAddrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIncentiveUnitIdsByAddrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIncentiveUnitIdsByAddrResponse proto.InternalMessageInfo

func (m *QueryIncentiveUnitIdsByAddrResponse) GetIncentiveUnitIdsByAddr() IncentiveUnitIdsByAddr {
	if m != nil {
		return m.IncentiveUnitIdsByAddr
	}
	return IncentiveUnitIdsByAddr{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ununifi.ecosystemincentive.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ununifi.ecosystemincentive.QueryParamsResponse")
	proto.RegisterType((*QueryIncentiveUnitRequest)(nil), "ununifi.ecosystemincentive.QueryIncentiveUnitRequest")
	proto.RegisterType((*QueryIncentiveUnitResponse)(nil), "ununifi.ecosystemincentive.QueryIncentiveUnitResponse")
	proto.RegisterType((*QueryAllRewardsRequest)(nil), "ununifi.ecosystemincentive.QueryAllRewardsRequest")
	proto.RegisterType((*QueryAllRewardsResponse)(nil), "ununifi.ecosystemincentive.QueryAllRewardsResponse")
	proto.RegisterType((*QueryRewardRequest)(nil), "ununifi.ecosystemincentive.QueryRewardRequest")
	proto.RegisterType((*QueryRewardResponse)(nil), "ununifi.ecosystemincentive.QueryRewardResponse")
	proto.RegisterType((*QueryRecordedIncentiveUnitIdRequest)(nil), "ununifi.ecosystemincentive.QueryRecordedIncentiveUnitIdRequest")
	proto.RegisterType((*QueryRecordedIncentiveUnitIdResponse)(nil), "ununifi.ecosystemincentive.QueryRecordedIncentiveUnitIdResponse")
	proto.RegisterType((*QueryIncentiveUnitIdsByAddrRequest)(nil), "ununifi.ecosystemincentive.QueryIncentiveUnitIdsByAddrRequest")
	proto.RegisterType((*QueryIncentiveUnitIdsByAddrResponse)(nil), "ununifi.ecosystemincentive.QueryIncentiveUnitIdsByAddrResponse")
}

func init() { proto.RegisterFile("ecosystemincentive/query.proto", fileDescriptor_12077848d3534579) }

var fileDescriptor_12077848d3534579 = []byte{
	// 947 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xce, 0x56, 0x8a, 0x43, 0x27, 0x4d, 0x4b, 0x27, 0x6d, 0x3e, 0x56, 0x95, 0x17, 0x86, 0x8a,
	0x7e, 0x00, 0x3b, 0xaa, 0x23, 0x2a, 0x28, 0x52, 0x9a, 0x2c, 0x52, 0x55, 0x23, 0x90, 0xe8, 0x42,
	0x0e, 0x70, 0xb1, 0xd6, 0xbb, 0x13, 0x67, 0xa8, 0x3d, 0xe3, 0x7a, 0xd6, 0xa5, 0x96, 0x65, 0x21,
	0x71, 0x83, 0x13, 0x12, 0xe2, 0xc0, 0x3f, 0x40, 0x88, 0x2b, 0x3f, 0x80, 0x0b, 0xea, 0xb1, 0x12,
	0x17, 0x4e, 0x06, 0x25, 0xfc, 0x00, 0xe4, 0x5f, 0x50, 0x79, 0xe6, 0xdd, 0xd8, 0xdb, 0x5d, 0x6f,
	0x9d, 0xaa, 0xa7, 0x78, 0x67, 0xe6, 0x7d, 0x3e, 0xde, 0x7d, 0xe7, 0xd9, 0xa0, 0x32, 0x0b, 0xa5,
	0xea, 0xa9, 0x98, 0xb5, 0xb8, 0x08, 0x99, 0x88, 0xf9, 0x43, 0x46, 0x1f, 0x74, 0x59, 0xa7, 0xe7,
	0xb6, 0x3b, 0x32, 0x96, 0xd8, 0xee, 0x8a, 0xae, 0xe0, 0xfb, 0xdc, 0xcd, 0x9e, 0xb3, 0x2f, 0x34,
	0x64, 0x43, 0xea, 0x63, 0x74, 0xfc, 0xcb, 0x54, 0xd8, 0x97, 0x1a, 0x52, 0x36, 0x9a, 0x8c, 0x06,
	0x6d, 0x4e, 0x03, 0x21, 0x64, 0x1c, 0xc4, 0x5c, 0x0a, 0x05, 0xbb, 0xd7, 0x43, 0xa9, 0x5a, 0x52,
	0xd1, 0x7a, 0xa0, 0x80, 0x88, 0x3e, 0xbc, 0x51, 0x67, 0x71, 0x70, 0x83, 0xb6, 0x83, 0x06, 0x17,
	0xfa, 0x30, 0x9c, 0x75, 0x72, 0xb4, 0xb5, 0x83, 0x4e, 0xd0, 0x4a, 0xc0, 0xde, 0xca, 0x39, 0x90,
	0x5d, 0x82, 0xc3, 0xe5, 0x69, 0xe6, 0x84, 0x33, 0x94, 0x1c, 0xd8, 0xc8, 0x05, 0x84, 0xef, 0x8d,
	0xf5, 0x7c, 0xaa, 0x19, 0x7c, 0xf6, 0xa0, 0xcb, 0x54, 0x4c, 0x0e, 0xd0, 0x6a, 0x6a, 0x55, 0xb5,
	0xa5, 0x50, 0x0c, 0xdf, 0x43, 0x25, 0xa3, 0x64, 0xc3, 0x7a, 0xcd, 0xba, 0xba, 0x5c, 0x21, 0xee,
	0xec, 0x3e, 0xb9, 0xa6, 0xd6, 0xbb, 0xf8, 0x78, 0xe8, 0x2c, 0x8c, 0x86, 0xce, 0x4a, 0x2f, 0x68,
	0x35, 0x6f, 0x11, 0x53, 0x4f, 0x7c, 0x00, 0x22, 0x0c, 0x6d, 0x6a, 0xa6, 0x6a, 0x52, 0xb7, 0x27,
	0x78, 0x0c, 0x32, 0xf0, 0x5d, 0x74, 0xfe, 0x18, 0xaf, 0xd6, 0x15, 0x3c, 0xae, 0xf1, 0x48, 0x53,
	0x9f, 0xf6, 0x2e, 0x8d, 0x86, 0xce, 0x86, 0x81, 0xcc, 0x1c, 0x21, 0xfe, 0x39, 0x3e, 0x0d, 0x57,
	0x8d, 0xc8, 0x77, 0x16, 0xb2, 0xf3, 0x78, 0xc0, 0xd8, 0x7d, 0x74, 0x36, 0x8d, 0x02, 0x06, 0xaf,
	0x15, 0x19, 0x4c, 0x41, 0x79, 0x9b, 0xa3, 0xa1, 0x73, 0x31, 0x4f, 0x10, 0xf1, 0x57, 0x52, 0x6a,
	0xc8, 0xe7, 0x68, 0x4d, 0x4b, 0xd9, 0x6d, 0x36, 0x7d, 0xf6, 0x75, 0xd0, 0x89, 0x92, 0xb6, 0xe3,
	0x5b, 0xe8, 0x8c, 0xea, 0xd6, 0xbf, 0x62, 0x61, 0x5c, 0x0b, 0xa2, 0xa8, 0x03, 0x56, 0xd7, 0x47,
	0x43, 0x67, 0xd5, 0x20, 0x4f, 0xef, 0x12, 0x7f, 0x19, 0x1e, 0x77, 0xc7, 0x4f, 0x31, 0x5a, 0xcf,
	0xa0, 0x82, 0xbb, 0x2f, 0xd0, 0x52, 0xc7, 0x2c, 0x81, 0xad, 0x2b, 0x45, 0xb6, 0x4c, 0xf5, 0x67,
	0xb1, 0xec, 0x30, 0x6f, 0x0d, 0x5e, 0xde, 0x59, 0x43, 0x0f, 0x28, 0xc4, 0x4f, 0xf0, 0xc8, 0x23,
	0x18, 0x1f, 0x53, 0xf4, 0x12, 0x7c, 0xe0, 0x37, 0xd1, 0x62, 0xc4, 0x84, 0x6c, 0x6d, 0x9c, 0xd2,
	0x45, 0xaf, 0x8e, 0x86, 0xce, 0x19, 0x53, 0xa4, 0x97, 0x89, 0x6f, 0xb6, 0xc9, 0xf7, 0x16, 0xcc,
	0x68, 0x42, 0x0d, 0x66, 0x15, 0x2a, 0x19, 0x71, 0xe0, 0x75, 0xd3, 0x35, 0x37, 0xc0, 0x1d, 0xdf,
	0x00, 0x17, 0x6e, 0x80, 0xfb, 0xa1, 0xe4, 0xc2, 0xdb, 0x49, 0x8f, 0xa6, 0x29, 0x23, 0xbf, 0xfe,
	0xe3, 0x5c, 0x69, 0xf0, 0xf8, 0xa0, 0x5b, 0x77, 0x43, 0xd9, 0xa2, 0x70, 0x7f, 0xcc, 0x9f, 0x77,
	0x54, 0x74, 0x9f, 0xc6, 0xbd, 0x36, 0x53, 0x1a, 0xc1, 0x07, 0x2a, 0xf2, 0x0d, 0x7a, 0x03, 0xb4,
	0x84, 0xb2, 0x13, 0xb1, 0xa8, 0x9a, 0x1e, 0xbf, 0xa4, 0x2f, 0x2e, 0x7a, 0x25, 0x6c, 0x06, 0x4a,
	0x4d, 0xc6, 0x78, 0x75, 0x34, 0x74, 0xce, 0x19, 0xfa, 0x64, 0x87, 0xf8, 0x4b, 0xfa, 0x67, 0x35,
	0xc2, 0x57, 0x51, 0x49, 0xec, 0xeb, 0xa1, 0x37, 0xcd, 0x38, 0x3f, 0x11, 0x6b, 0xd6, 0x89, 0xbf,
	0x28, 0xf6, 0xc7, 0xf3, 0xdd, 0x46, 0x97, 0x8b, 0x05, 0x40, 0x77, 0x5e, 0xde, 0x8d, 0xf2, 0x11,
	0xc9, 0x5e, 0xa8, 0x6a, 0xa4, 0xbc, 0xde, 0xf8, 0x35, 0x26, 0x8e, 0xdf, 0x46, 0x4b, 0xe3, 0x77,
	0xcc, 0x94, 0x02, 0x16, 0x3c, 0x99, 0x26, 0xd8, 0x20, 0x7e, 0x72, 0x84, 0xfc, 0x61, 0x41, 0x1f,
	0x67, 0x81, 0x82, 0x8b, 0x9f, 0x2d, 0x64, 0x67, 0x34, 0xaa, 0x5a, 0xbd, 0x37, 0x19, 0xb7, 0xe5,
	0x4a, 0x65, 0xee, 0xbb, 0x7b, 0x4c, 0xe0, 0x5d, 0x83, 0x89, 0x78, 0x7d, 0x46, 0x1f, 0x8e, 0x39,
	0x88, 0xbf, 0xc6, 0x73, 0x21, 0x2a, 0xbf, 0x9c, 0x46, 0x8b, 0xda, 0x03, 0xfe, 0xc9, 0x42, 0x25,
	0x13, 0x82, 0xd8, 0x2d, 0xd2, 0x92, 0xcd, 0x5f, 0x9b, 0xce, 0x7d, 0xde, 0x74, 0x84, 0x5c, 0xff,
	0xf6, 0xaf, 0xff, 0x7e, 0x3c, 0x75, 0x19, 0x13, 0x0a, 0x85, 0x74, 0xe6, 0x57, 0x04, 0xff, 0x69,
	0xa1, 0x95, 0x94, 0x7f, 0xfc, 0xee, 0x73, 0xe9, 0xf2, 0xe2, 0xd9, 0xbe, 0x79, 0xd2, 0x32, 0x10,
	0x7b, 0x47, 0x8b, 0xdd, 0xc1, 0xdb, 0x45, 0x62, 0xd3, 0xbd, 0xa7, 0xfd, 0xcc, 0xbb, 0x18, 0xe0,
	0xdf, 0x2d, 0x84, 0x26, 0x71, 0x87, 0x2b, 0xcf, 0x95, 0x93, 0x49, 0x5c, 0x7b, 0xeb, 0x44, 0x35,
	0xa0, 0x7f, 0x5b, 0xeb, 0x7f, 0x0f, 0xdf, 0x2c, 0xd2, 0x1f, 0x34, 0x9b, 0x35, 0x48, 0x49, 0xda,
	0x9f, 0xce, 0xbb, 0x01, 0xfe, 0xcd, 0x42, 0x25, 0x83, 0x39, 0xc7, 0x60, 0xa4, 0x92, 0x75, 0x8e,
	0xc1, 0x48, 0xc7, 0x21, 0xd9, 0xd5, 0x5a, 0x3f, 0xc0, 0xef, 0x17, 0x69, 0x35, 0x3a, 0x9f, 0x91,
	0x49, 0xfb, 0x3a, 0x68, 0x07, 0xf8, 0x7f, 0x0b, 0xad, 0xcf, 0xc8, 0x15, 0x7c, 0x7b, 0x0e, 0x3d,
	0x45, 0x91, 0x68, 0xef, 0xbc, 0x38, 0x00, 0x38, 0xf4, 0xb5, 0xc3, 0x8f, 0xf1, 0x47, 0xc5, 0x0e,
	0x0d, 0x48, 0x2d, 0x33, 0x46, 0xb4, 0x9f, 0x04, 0xef, 0x80, 0xf6, 0x4d, 0xaa, 0x0e, 0xf0, 0x91,
	0x85, 0xd6, 0xf2, 0x23, 0x02, 0x6f, 0x9f, 0x6c, 0xe8, 0x9f, 0x4d, 0x44, 0xfb, 0xf6, 0x0b, 0xd7,
	0x83, 0xdf, 0xbb, 0xda, 0xaf, 0x87, 0x77, 0xe6, 0xbf, 0x3d, 0xd3, 0xc9, 0x45, 0xfb, 0x90, 0xb6,
	0x03, 0xef, 0x93, 0xc7, 0x87, 0x65, 0xeb, 0xc9, 0x61, 0xd9, 0xfa, 0xf7, 0xb0, 0x6c, 0xfd, 0x70,
	0x54, 0x5e, 0x78, 0x72, 0x54, 0x5e, 0xf8, 0xfb, 0xa8, 0xbc, 0xf0, 0xe5, 0xd6, 0xd4, 0x07, 0x70,
	0x4f, 0xec, 0x09, 0x7e, 0x87, 0xd3, 0xf0, 0x20, 0xe0, 0x82, 0x3e, 0xca, 0x63, 0xd3, 0x5f, 0xc4,
	0x7a, 0x49, 0xff, 0x47, 0xb9, 0xf5, 0x34, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xf0, 0x1b, 0x7d, 0x5d,
	0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	IncentiveUnit(ctx context.Context, in *QueryIncentiveUnitRequest, opts ...grpc.CallOption) (*QueryIncentiveUnitResponse, error)
	AllRewards(ctx context.Context, in *QueryAllRewardsRequest, opts ...grpc.CallOption) (*QueryAllRewardsResponse, error)
	Reward(ctx context.Context, in *QueryRewardRequest, opts ...grpc.CallOption) (*QueryRewardResponse, error)
	RecordedIncentiveUnitId(ctx context.Context, in *QueryRecordedIncentiveUnitIdRequest, opts ...grpc.CallOption) (*QueryRecordedIncentiveUnitIdResponse, error)
	IncentiveUnitIdsByAddr(ctx context.Context, in *QueryIncentiveUnitIdsByAddrRequest, opts ...grpc.CallOption) (*QueryIncentiveUnitIdsByAddrResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ununifi.ecosystemincentive.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IncentiveUnit(ctx context.Context, in *QueryIncentiveUnitRequest, opts ...grpc.CallOption) (*QueryIncentiveUnitResponse, error) {
	out := new(QueryIncentiveUnitResponse)
	err := c.cc.Invoke(ctx, "/ununifi.ecosystemincentive.Query/IncentiveUnit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllRewards(ctx context.Context, in *QueryAllRewardsRequest, opts ...grpc.CallOption) (*QueryAllRewardsResponse, error) {
	out := new(QueryAllRewardsResponse)
	err := c.cc.Invoke(ctx, "/ununifi.ecosystemincentive.Query/AllRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Reward(ctx context.Context, in *QueryRewardRequest, opts ...grpc.CallOption) (*QueryRewardResponse, error) {
	out := new(QueryRewardResponse)
	err := c.cc.Invoke(ctx, "/ununifi.ecosystemincentive.Query/Reward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RecordedIncentiveUnitId(ctx context.Context, in *QueryRecordedIncentiveUnitIdRequest, opts ...grpc.CallOption) (*QueryRecordedIncentiveUnitIdResponse, error) {
	out := new(QueryRecordedIncentiveUnitIdResponse)
	err := c.cc.Invoke(ctx, "/ununifi.ecosystemincentive.Query/RecordedIncentiveUnitId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IncentiveUnitIdsByAddr(ctx context.Context, in *QueryIncentiveUnitIdsByAddrRequest, opts ...grpc.CallOption) (*QueryIncentiveUnitIdsByAddrResponse, error) {
	out := new(QueryIncentiveUnitIdsByAddrResponse)
	err := c.cc.Invoke(ctx, "/ununifi.ecosystemincentive.Query/IncentiveUnitIdsByAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	IncentiveUnit(context.Context, *QueryIncentiveUnitRequest) (*QueryIncentiveUnitResponse, error)
	AllRewards(context.Context, *QueryAllRewardsRequest) (*QueryAllRewardsResponse, error)
	Reward(context.Context, *QueryRewardRequest) (*QueryRewardResponse, error)
	RecordedIncentiveUnitId(context.Context, *QueryRecordedIncentiveUnitIdRequest) (*QueryRecordedIncentiveUnitIdResponse, error)
	IncentiveUnitIdsByAddr(context.Context, *QueryIncentiveUnitIdsByAddrRequest) (*QueryIncentiveUnitIdsByAddrResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) IncentiveUnit(ctx context.Context, req *QueryIncentiveUnitRequest) (*QueryIncentiveUnitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncentiveUnit not implemented")
}
func (*UnimplementedQueryServer) AllRewards(ctx context.Context, req *QueryAllRewardsRequest) (*QueryAllRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllRewards not implemented")
}
func (*UnimplementedQueryServer) Reward(ctx context.Context, req *QueryRewardRequest) (*QueryRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reward not implemented")
}
func (*UnimplementedQueryServer) RecordedIncentiveUnitId(ctx context.Context, req *QueryRecordedIncentiveUnitIdRequest) (*QueryRecordedIncentiveUnitIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordedIncentiveUnitId not implemented")
}
func (*UnimplementedQueryServer) IncentiveUnitIdsByAddr(ctx context.Context, req *QueryIncentiveUnitIdsByAddrRequest) (*QueryIncentiveUnitIdsByAddrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncentiveUnitIdsByAddr not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ununifi.ecosystemincentive.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IncentiveUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIncentiveUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IncentiveUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ununifi.ecosystemincentive.Query/IncentiveUnit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IncentiveUnit(ctx, req.(*QueryIncentiveUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ununifi.ecosystemincentive.Query/AllRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllRewards(ctx, req.(*QueryAllRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Reward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Reward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ununifi.ecosystemincentive.Query/Reward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Reward(ctx, req.(*QueryRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RecordedIncentiveUnitId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecordedIncentiveUnitIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecordedIncentiveUnitId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ununifi.ecosystemincentive.Query/RecordedIncentiveUnitId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecordedIncentiveUnitId(ctx, req.(*QueryRecordedIncentiveUnitIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IncentiveUnitIdsByAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIncentiveUnitIdsByAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IncentiveUnitIdsByAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ununifi.ecosystemincentive.Query/IncentiveUnitIdsByAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IncentiveUnitIdsByAddr(ctx, req.(*QueryIncentiveUnitIdsByAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ununifi.ecosystemincentive.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "IncentiveUnit",
			Handler:    _Query_IncentiveUnit_Handler,
		},
		{
			MethodName: "AllRewards",
			Handler:    _Query_AllRewards_Handler,
		},
		{
			MethodName: "Reward",
			Handler:    _Query_Reward_Handler,
		},
		{
			MethodName: "RecordedIncentiveUnitId",
			Handler:    _Query_RecordedIncentiveUnitId_Handler,
		},
		{
			MethodName: "IncentiveUnitIdsByAddr",
			Handler:    _Query_IncentiveUnitIdsByAddr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecosystemincentive/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryIncentiveUnitRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIncentiveUnitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIncentiveUnitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IncentiveUnitId) > 0 {
		i -= len(m.IncentiveUnitId)
		copy(dAtA[i:], m.IncentiveUnitId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IncentiveUnitId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIncentiveUnitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIncentiveUnitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIncentiveUnitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IncentiveUnit != nil {
		{
			size, err := m.IncentiveUnit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRewardsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRewardsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRewardsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubjectAddr) > 0 {
		i -= len(m.SubjectAddr)
		copy(dAtA[i:], m.SubjectAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SubjectAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Rewards.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRewardRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SubjectAddr) > 0 {
		i -= len(m.SubjectAddr)
		copy(dAtA[i:], m.SubjectAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SubjectAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Reward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRecordedIncentiveUnitIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecordedIncentiveUnitIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecordedIncentiveUnitIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftId) > 0 {
		i -= len(m.NftId)
		copy(dAtA[i:], m.NftId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NftId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecordedIncentiveUnitIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecordedIncentiveUnitIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecordedIncentiveUnitIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IncentiveUnitId) > 0 {
		i -= len(m.IncentiveUnitId)
		copy(dAtA[i:], m.IncentiveUnitId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IncentiveUnitId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIncentiveUnitIdsByAddrRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIncentiveUnitIdsByAddrRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIncentiveUnitIdsByAddrRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIncentiveUnitIdsByAddrResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIncentiveUnitIdsByAddrResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIncentiveUnitIdsByAddrResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.IncentiveUnitIdsByAddr.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryIncentiveUnitRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IncentiveUnitId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIncentiveUnitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IncentiveUnit != nil {
		l = m.IncentiveUnit.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRewardsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubjectAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Rewards.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRewardRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SubjectAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRewardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Reward.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRecordedIncentiveUnitIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.NftId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecordedIncentiveUnitIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IncentiveUnitId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIncentiveUnitIdsByAddrRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIncentiveUnitIdsByAddrResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.IncentiveUnitIdsByAddr.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIncentiveUnitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIncentiveUnitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIncentiveUnitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncentiveUnitId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncentiveUnitId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIncentiveUnitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIncentiveUnitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIncentiveUnitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncentiveUnit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.IncentiveUnit == nil {
				m.IncentiveUnit = &IncentiveUnit{}
			}
			if err := m.IncentiveUnit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRewardsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRewardsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRewardsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecordedIncentiveUnitIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecordedIncentiveUnitIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecordedIncentiveUnitIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecordedIncentiveUnitIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecordedIncentiveUnitIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecordedIncentiveUnitIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncentiveUnitId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IncentiveUnitId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIncentiveUnitIdsByAddrRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIncentiveUnitIdsByAddrRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIncentiveUnitIdsByAddrRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIncentiveUnitIdsByAddrResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIncentiveUnitIdsByAddrResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIncentiveUnitIdsByAddrResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IncentiveUnitIdsByAddr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IncentiveUnitIdsByAddr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
