name: Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
    #        include:
    #          - targetos: windows
    #            arch: amd64
    name: ununifi-${{ matrix.arch }}-${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - run: |
          go mod download
          cd cmd/ununifid
          go build .
      - uses: actions/upload-artifact@v2
        with:
          name: ununifid-${{ matrix.targetos }}-${{ matrix.arch }}
          path: cmd/ununifid/ununifid
